version: "3.6"
services:
  httpd:
    build: 
      context: .
      dockerfile: ./docker/httpd/Dockerfile
    command: [ "-l" ]
    depends_on:
      - postgres
    shm_size: 1gb
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_PASSWORD=otrs
      - POSTGRES_USER=otrs
      - POSTGRES_DB=otrs
      - ORACLE_HOME=/opt/oracle/instantclient_19_16
      - TNS_ADMIN=/opt/oracle/instantclient_19_16/network/admin
      - NLS_LANG=American_America.UTF8
      - OTRS_PASSWORD=${OTRS_PASSWORD:-otrs}
      - OTRS_FQDN=localhost:8090
      - OTRS_HTTPTYPE=http
      - OTRS_ADMINEMAIL=${OTRS_ADMINEMAIL:-root@localhost}
    volumes: 
      #- type: bind
      #  source: ./znuny
      #  target: /opt/otrs/
      #- type: bind
      #  source: ./docker/httpd
      #  target: /opt/docker/httpd
      - type: volume
        source: article
        target: /opt/otrs/var/article
      - type: tmpfs
        target: /opt/otrs/var/tmp
    ports:
      - "8090:80"
    networks:
      - network
    extra_hosts:
      - host.docker.internal:host-gateway
  postgres:
    build: 
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    shm_size: 256mb
    environment:
      - POSTGRES_PASSWORD=otrs
      - POSTGRES_USER=otrs
      - POSTGRES_DB=otrs
    volumes:
      - type: volume
        source: postgres
        target: /var/lib/postgresql/data
    networks:
      - network
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@localhost.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - "pgadmin:/var/lib/pgadmin"
    ports:
      - "8099:80"
    networks:
      - network
networks:
  network:
volumes:
  postgres:
  pgadmin:
  article: